Reporting an issue
===============================================================================

First please make sure whether is unknown/not reported yet:

* Validate it is an issue on PyPoE's end and not just a coding mistake on your
  end
* Make sure you are running the latest version of PyPoE
* Check open github issues: https://github.com/OmegaK2/PyPoE/issues
* Check the "TODO"s in the affected file or function

After taking those steps please report the issue to github and provide as
much information as you can:

* Title: Short, but definitive description of the bug
* Description: Detailed description of the bug, in particular steps on how to
  reproduce it
* if available, provide the relevant python traceback
* if available, provide the relevant code that caused the bug

You can also submit pull requests that to help fix bugs, I'll review (and
possibly) edit them. You agree they'll placed under the MIT license (for more
info see :doc:`contribution`)